name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'    # ensure submodules (and nested submodules) are checked out
        fetch-depth: 0             # get full history
        persist-credentials: true  # allow use of $GITHUB_TOKEN for submodule fetch
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Init and update submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
